name: Update Release Notes

on:
  release:
    types: [published]

permissions:
  contents: write  # Required for accessing and updating releases

jobs:
  update-release-notes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get the latest release notes using GitHub API
      - name: Get latest release details
        id: release_details
        run: |
          release_data=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_notes=$(echo $release_data | jq -r '.body')

          echo "release_notes=$release_notes" >> $GITHUB_ENV

      # Step 3: Append text to the release notes
      - name: Append text to release notes
        run: |
          updated_notes="${{ env.release_notes }}\n\nupdated by gh action"
          
          # Update release with new notes using GitHub API
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"$updated_notes\"}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
