name: Update Release Notes

on:
  release:
    types:
      - published  # Trigger when a new release is published

jobs:
  get-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch release notes of latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the release tag from the event payload
          TAG_NAME=$(jq -r '.release.tag_name' < "$GITHUB_EVENT_PATH")
          echo "Release tag: $TAG_NAME"

          # Fetch the release data using GitHub API
          RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME")

          # Extract the release notes (raw body)
          RELEASE_NOTES=$(echo "$RELEASE" | jq -r '.body')

          # Output the release notes to the logs
          echo "Release Notes:\n$RELEASE_NOTES"
